name: ROS 2 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ros-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: f1tenth_rl
          target-ros2-distro: humble
          vcs-repo-file-url: "" # 外部リポジトリがない場合は空
